export const MENU_LIST = [
  {
    id: '1',
    title: 'Button 按钮',
    name: 'Button',
    path: '/button',
    cpoPath: 'button/Index',
    key: '1',
    meta: { tabName: 'PondGroup' },
  },
  {
    id: '2',
    title: 'Upload 上传',
    name: 'Upload',
    path: '/upload',
    cpoPath: 'upload/Index',
    key: '2',
  },
  {
    id: '3',
    title: 'Descriptions 描述',
    name: 'Descriptions',
    path: '/descriptions',
    cpoPath: 'descriptions/Index',
    key: '3',
  },
  {
    id: '4',
    title: 'Form 表单',
    name: 'Form',
    path: '/form',
    cpoPath: 'form/Index',
    key: '4',
  },
  {
    id: '5',
    title: 'Preview 预览',
    name: 'Preview',
    path: '/preview',
    cpoPath: 'preview/Index',
    key: '5',
  },
  {
    id: '6',
    title: 'Menu 菜单',
    name: 'Menu',
    path: '/menu',
    cpoPath: 'menu/Index',
    key: '6',
  },
  {
    id: '7',
    title: 'Table 表格',
    name: 'Table',
    path: '/table',
    cpoPath: 'table/Index',
    key: '7',
  },
  {
    id: '8',
    title: 'Confirm 确认框',
    name: 'Confirm',
    path: '/confirm',
    cpoPath: 'confirm/Index',
    key: '8',
  },
  {
    id: '9',
    title: 'Chart 图表',
    name: 'Chart',
    path: '/chart',
    cpoPath: 'chart/Index',
    key: '9',
  },
  {
    id: '10',
    title: 'Tree 树',
    name: 'Tree',
    path: '/tree',
    cpoPath: 'tree/Index',
    key: '10',
  },
  {
    id: '12',
    title: 'Map 地图',
    name: 'Map',
    path: '/map',
    cpoPath: 'map/Index',
    key: '12',
  },
  {
    id: '13',
    title: 'Editor 富文本编辑器',
    name: 'Editor',
    path: '/editor',
    cpoPath: 'editor/Index',
    key: '13',
  },
  {
    id: '15',
    title: 'Dialog 弹窗',
    name: 'Dialog',
    path: '/dialog',
    cpoPath: 'dialog/Index',
    key: '15',
  },
  {
    id: '16',
    title: 'Layout 布局',
    name: 'LSLayout',
    path: '/lsLayout',
    cpoPath: 'lsLayout/Index',
    key: '16',
  },
  {
    id: '17',
    title: 'List 列表',
    name: 'List',
    path: '/list',
    cpoPath: 'list/Index',
    key: '17',
  },
  {
    id: '18',
    title: 'DownloadFile 下载文件',
    name: 'DownloadFile',
    path: '/downloadFile',
    cpoPath: 'downloadFile/Index',
    key: '18',
  },
  {
    id: '23',
    title: 'SliceUpload 分片上传',
    name: 'SliceUpload',
    path: '/sliceUpload',
    cpoPath: 'sliceUpload/Index',
    key: '23',
  },
  // list切换报错测试
  {
    id: '19',
    title: 'List测试页面1',
    name: 'List1',
    path: '/list1',
    cpoPath: 'list/List1',
    key: '19',
  },
  {
    id: '20',
    title: 'List测试页面2',
    name: 'List2',
    path: '/list2',
    cpoPath: 'list/List2',
    key: '20',
  },
  {
    id: '21',
    title: 'Cropper 剪裁',
    name: 'Cropper',
    path: '/cropper',
    cpoPath: 'cropper/Index',
    key: '21',
  },
  {
    id: '22',
    title: 'CaptchaVerify 验证码',
    name: 'CaptchaVerify',
    path: '/captchaVerify',
    cpoPath: 'captchaVerify/Index',
    key: '22',
  },
  {
    id: '24',
    title: 'BackTop 回到顶部',
    name: 'BackTop',
    path: '/backTop',
    cpoPath: 'backTop/Index',
    key: '24',
  },
  {
    id: '25',
    title: 'BellMessage 消息铃铛',
    name: 'BellMessage',
    path: '/bellMessage',
    cpoPath: 'bellMessage/Index',
    key: '25',
  },
  {
    id: '26',
    title: 'Breadcrumb 面包屑',
    name: 'Breadcrumb',
    path: '/breadcrumb',
    cpoPath: 'breadcrumb/Index',
    key: '26',
  },
  {
    id: '27',
    title: 'ContainerBox 容器盒子',
    name: 'ContainerBox',
    path: '/containerBox',
    cpoPath: 'containerBox/Index',
    key: '27',
  },
  {
    id: '28',
    title: 'Icon 图标',
    name: 'Icon',
    path: '/icon',
    cpoPath: 'icon/Index',
    key: '28',
  },
  {
    id: '29',
    title: 'Live 视频直播',
    name: 'Live',
    path: '/live',
    cpoPath: 'live/Index',
    key: '29',
  },
  {
    id: '30',
    title: 'Print 打印',
    name: 'Print',
    path: '/print',
    cpoPath: 'print/Index',
    key: '30',
  },
  {
    id: '31',
    title: 'Tooltip 工具提示',
    name: 'Tooltip',
    path: '/tooltip',
    cpoPath: 'tooltip/Index',
    key: '31',
  },
  {
    id: '32',
    title: 'Theme 主题',
    name: 'Theme',
    path: '/theme',
    cpoPath: 'theme/Index',
    key: '32',
  },
]

export const MonthDays = Array.from({ length: 31 }, (_, index) => `${index + 1}日`)

export const MonthDayOptions = MonthDays.map((item: string, i: number) => {
  return {
    value: i + 1,
    label: item,
  }
})
