name: LSWeb PUBLISH

on:
  push:
    branches: [main]

jobs:
  build:
    name: 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
        
      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build
        run: |
          npm run build:ls-components

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
            name: build-artifact
            path: packages/ls-components/lib
  
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Reset .gitignore
        run: git checkout -- .gitignore
