name: LSWeb PUBLISH

on:
  push:
    branches: [main]

jobs:
  build:
    name: 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
        
      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build
        run: |
          npm run build:ls-components

      - name: Use built files
        run: ls packages/ls-components/lib

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
